version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore C:\projects\quidjibo\src\Quidjibo.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
artifacts:
- path: '**\*.nupkg'